#!/usr/bin/env bash
set -euo pipefail

echo "IMPERIOR Zone 14 — final filename cleanup"
git mv "imp-14-02-01-master-plan-imperior-kampusa.md" "imp-14-02-01-okvir-rezidencijalnog-sustava-kampusa.md"
git mv "imp-14-02-02-standard-prostornog-razvoja-kampusa.md" "imp-14-02-02-standard-stanovanja-i-rezidencijalnih-jedinica.md"
git mv "imp-14-02-03-registar-objekata-i-prostornih-cjelina.md" "imp-14-02-03-registar-rezidencijalnih-kapaciteta.md"
git mv "imp-14-03-01-okvir-stambenog-sustava-kampusa.md" "imp-14-03-01-okvir-zdravstvenih-i-wellness-sadrzaja-kampusa.md"
git mv "imp-14-03-02-standard-stanovanja.md" "imp-14-03-02-standard-zdravstvenih-i-wellness-usluga.md"
git mv "imp-14-03-03-plan-upravljanja-stambenim-kapacitetima.md" "imp-14-03-03-plan-koordinacije-zdravstvene-i-wellness-skrbi.md"
git mv "imp-14-04-01-okvir-zdravstvenih-usluga-kampusa.md" "imp-14-04-01-okvir-obrazovnih-i-istrazivackih-sadrzaja-kampusa.md"
git mv "imp-14-04-02-standard-wellness-i-preventivnih-programa.md" "imp-14-04-02-standard-obrazovnih-i-istrazivackih-centara.md"
git mv "imp-14-04-03-koordinacija-zdravstvene-skrbi-kampusa.md" "imp-14-04-03-program-razvoja-znanja-i-inovacija-kampusa.md"
git mv "imp-14-05-01-okvir-obrazovnih-sadrzaja-kampusa.md" "imp-14-05-01-okvir-javnih-i-drustvenih-sadrzaja-kampusa.md"
git mv "imp-14-05-02-standard-istrazivackih-centara-kampusa.md" "imp-14-05-02-standard-javnih-usluga-i-drustvenih-sadrzaja.md"
git mv "imp-14-05-03-program-razvoja-znanja-i-inovacija.md" "imp-14-05-03-registar-javnih-drustvenih-i-usluznih-sadrzaja.md"
git mv "imp-14-06-01-model-javnih-usluga-kampusa.md" "imp-14-06-01-sigurnosni-plan-imperior-kampusa.md"
git mv "imp-14-06-02-standard-trgovine-i-usluga-kampusa.md" "imp-14-06-02-standard-kontrole-pristupa-i-zastite-kampusa.md"
git mv "imp-14-06-03-registar-usluznih-sadrzaja.md" "imp-14-06-03-protokol-kriznog-odgovora-kampusa.md"
git mv "imp-14-07-01-sigurnosni-plan-imperior-kampusa.md" "imp-14-07-01-plan-prometa-logistike-i-pristupa-kampusu.md"
git mv "imp-14-07-02-standard-kontrole-pristupa.md" "imp-14-07-02-standard-unutarnjeg-prometa-i-logistike.md"
git mv "imp-14-07-03-protokol-kriznog-odgovora-kampusa.md" "imp-14-07-03-upravljanje-parkiralisnim-i-transportnim-kapacitetima.md"
git mv "imp-14-08-01-plan-mobilnosti-kampusa.md" "imp-14-08-01-plan-zelenih-povrsina-i-rekreacije-kampusa.md"
git mv "imp-14-08-02-standard-unutarnjeg-prometnog-sustava.md" "imp-14-08-02-standard-sportskih-i-rekreacijskih-sadrzaja.md"
git mv "imp-14-08-03-upravljanje-parkiralisnim-i-transportnim-kapacitetima.md" "imp-14-08-03-program-odrzavanja-zelenih-i-rekreacijskih-povrsina.md"
git mv "imp-14-09-01-program-kulturnog-zivota-kampusa.md" "imp-14-09-01-strategija-digitalne-infrastrukture-kampusa.md"
git mv "imp-14-09-02-standard-sportskih-i-rekreacijskih-sadrzaja.md" "imp-14-09-02-standard-digitalnih-sustava-i-povezivosti-kampusa.md"
git mv "imp-14-09-03-program-razvoja-zajednice-kampusa.md" "imp-14-09-03-plan-upravljanja-digitalnom-infrastrukturom-kampusa.md"

echo "Done. Review with: git status"
